pipeline:
  publish_prod:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Containerfile
      platforms: 
        - linux/amd64
        - linux/arm/v7
      repo:
        from_secret: TARGET_REPOSITORY
      registry:
        from_secret: REGISTRY_HOST
      tags: latest
      username: 
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
    when:
      event: push
      branch: main

  depl_prod:
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SERVER_HOST
      username:
        from_secret: SERVER_USER
      key:
        from_secret: SERVER_KEY
      port: 22
      script:
        from_secret: PROD_DEPLOYMENT_NAME
    when:
      event: push
      branch: main

  publish_dev:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Containerfile
      platforms: 
        - linux/amd64
        - linux/arm/v7
      repo:
        from_secret: TARGET_REPOSITORY
      registry:
        from_secret: REGISTRY_HOST
      tags: latest
      username: 
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
    when:
      event: push
      branch: dev

  depl_dev:
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SERVER_HOST
      username:
        from_secret: SERVER_USER
      key:
        from_secret: SERVER_KEY
      port: 22
      script:
        from_secret: DEV_DEPLOYMENT_NAME
    when:
      event: push
      branch: dev
